<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-T6SC6MV" failures="1" tests="1" name="Test(failed)" time="0.095" errors="0" timestamp="2023-01-21T11:29:10 IST">
  <testcase classname="batchExecution.SecondTest" name="demo" time="0.018">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at batchExecution.SecondTest.demo(SecondTest.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
</testsuite> <!-- Test(failed) -->
